#!/usr/bin/env python3
"""
AI Video Factory v1.0.0 — Human Operator Runbook Generator
Generates the complete 04_TOOLING/prompts/implementation/AVF_OPERATOR_RUNBOOK_v1.0.0/ pack.
"""

import os
import sys
import yaml
import json

BASE_DIR = "/Applications/XAMPP/xamppfiles/htdocs/AGENTIC/AVF_SPEC_REVIEW"
RUNBOOK_DIR = os.path.join(BASE_DIR, "04_TOOLING/prompts/implementation/AVF_OPERATOR_RUNBOOK_v1.0.0")

# 15 Repos definition
REPOS_DATA = [
    {
        "id": "R01",
        "folder": "02_R01_CONTRACTS",
        "name": "R01_contracts",
        "display_name": "Contracts & Typed Schemas",
        "layer": "Layer 0",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R01_CONTRACTS.md",
        "contracts": [
            "02_contracts/domain-entities.schema.json",
            "02_contracts/event-envelope.schema.json",
            "02_contracts/provider-request.schema.json",
            "02_contracts/provider-result.schema.json",
            "02_contracts/browser-command.schema.json",
            "02_contracts/flow-execution-result.schema.json"
        ],
        "deps": [],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R14", "R15", "Direct DB"],
        "owns": "JSON Schemas, TypeScript type generation, JSON fixture test suite, FlowExecutionPort conformance test suite",
        "does_not_own": "Runtime execution, database connections, UI components, external API calling",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Claude Opus 4.6 Thinking",
        "accept_model_fallback": "Gemini 3.1 Pro High",
        "pass_next": "R14-01",
        "hardening_notes": "Apply R01_PREIMPLEMENTATION_HARDENING.md: $defs standardization, 17 execution stages, discriminated unions for FlowExecutionResult, positive/negative fixtures >=3 each, Track A & B common conformance suite."
    },
    {
        "id": "R14",
        "folder": "15_R14_OBSERVABILITY",
        "name": "R14_platform_observability",
        "display_name": "Observability, Telemetry & Security",
        "layer": "Cross-Cutting",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R14_PLATFORM_OBSERVABILITY.md",
        "contracts": ["event-envelope.schema.json"],
        "deps": ["R01"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R15", "Direct DB"],
        "owns": "OpenTelemetry tracing SDK wrapper, correlation context propagation, secret & token redaction engine, structured log formatter, Prometheus metrics exporter",
        "does_not_own": "Domain persistence, business logic, workflow execution, provider calls",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Gemini 3.1 Pro High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R02-01",
        "hardening_notes": "Zero secrets in logs; automated redaction filter for Bearer tokens, cookies, passwords; distributed trace context injection."
    },
    {
        "id": "R02",
        "folder": "03_R02_CORE_STATE",
        "name": "R02_core_state",
        "display_name": "Core State & Persistence Engine",
        "layer": "Layer 1",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R02_CORE_STATE.md",
        "contracts": ["domain-entities.schema.json", "event-envelope.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R15"],
        "owns": "PostgreSQL schema migrations, Prisma/Drizzle models, GenerationJob state machine, 17 execution stages, Idempotency store, entity CRUD API",
        "does_not_own": "Temporal workflow execution, video generation, browser automation, creative script generation",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Gemini 3.1 Pro High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R07-01",
        "hardening_notes": "Enforce INV-001 through INV-012, deterministic state transitions, idempotency key uniqueness, sole owner of PostgreSQL connection."
    },
    {
        "id": "R07",
        "folder": "04_R07_PROVIDER_SDK",
        "name": "R07_provider_sdk",
        "display_name": "Provider Neutral SDK & FakeProvider",
        "layer": "Layer 3",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R07_PROVIDER_SDK.md",
        "contracts": ["provider-request.schema.json", "provider-result.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R08", "R09", "R10", "R11", "R12", "R13", "R15", "Direct DB"],
        "owns": "VideoProvider interface abstraction, capability matrix parser, normalized 9-error taxonomy, FakeVideoProvider with full simulation matrix",
        "does_not_own": "PostgreSQL persistence, Google Flow specific automation, Temporal workflows",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Gemini 3.1 Pro High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "GATE-00",
        "hardening_notes": "FakeVideoProvider must support success(0s), success(30s), fail_transient(2), fail_provider, rate_limit, timeout, status_unknown, corrupt_output."
    },
    {
        "id": "R06",
        "folder": "05_R06_WORKFLOW",
        "name": "R06_workflow",
        "display_name": "Temporal Workflow Orchestrator",
        "layer": "Layer 5",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R06_WORKFLOW.md",
        "contracts": ["domain-entities.schema.json", "event-envelope.schema.json", "provider-request.schema.json"],
        "deps": ["R01", "R02", "R03", "R04", "R05", "R07", "R08", "R11", "R12", "R14"],
        "forbidden": ["R09", "R10", "Direct DB"],
        "owns": "Temporal workflow definitions (SingleShot, MultiShot, RenderPipeline), retry policy engine, activity handlers, reconciliation logic",
        "does_not_own": "Database tables directly, browser automation, raw video rendering, UI rendering",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Claude Opus 4.6 Thinking",
        "accept_model_fallback": "Gemini 3.1 Pro High",
        "pass_next": "R15-01",
        "hardening_notes": "Temporal replay safety, deterministic workflows, exponential backoff with jitter, idempotency token persistence."
    },
    {
        "id": "R15",
        "folder": "06_R15_INTEGRATION_HARNESS",
        "name": "R15_integration_harness",
        "display_name": "End-to-End Integration & Scenario Test Harness",
        "layer": "Cross-Cutting",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R15_INTEGRATION_HARNESS.md",
        "contracts": ["domain-entities.schema.json", "event-envelope.schema.json", "provider-request.schema.json", "provider-result.schema.json", "browser-command.schema.json", "flow-execution-result.schema.json"],
        "deps": ["R01", "R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R14"],
        "forbidden": ["Direct production DB mutation"],
        "owns": "16 chaos/fault-injection scenarios, E2E test runner, offline test orchestration, golden test fixture assertions",
        "does_not_own": "Production runtime services, application logic",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Gemini 3.1 Pro High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "GATE-01",
        "hardening_notes": "Simulate worker kill before submit, kill after submit, uncertain outcome, duplicate delivery, auth expired, corrupt output."
    },
    {
        "id": "R08",
        "folder": "07_R08_GOOGLE_FLOW_ADAPTER",
        "name": "R08_google_flow_adapter",
        "display_name": "Google Flow Provider Adapter",
        "layer": "Layer 3",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R08_GOOGLE_FLOW_ADAPTER.md",
        "contracts": ["provider-request.schema.json", "provider-result.schema.json", "browser-command.schema.json", "flow-execution-result.schema.json"],
        "deps": ["R01", "R07", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "Direct DB"],
        "owns": "Google Flow adapter implementing VideoProvider interface, FlowExecutionPort client caller, prompt/aspect translation",
        "does_not_own": "Direct browser automation code, WebSocket network parsing, database access",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Claude Opus 4.6 Thinking",
        "accept_model_fallback": "Gemini 3.1 Pro High",
        "pass_next": "R10-01",
        "hardening_notes": "Isolate FlowExecutionPort abstraction so Track A (R09) and Track B (R10) can be swapped seamlessly."
    },
    {
        "id": "R10",
        "folder": "08_R10_FLOWKIT_BRIDGE",
        "name": "R10_flowkit_bridge",
        "display_name": "Track B Direct FlowKit Bridge",
        "layer": "Layer 4",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R10_FLOWKIT_BRIDGE.md",
        "contracts": ["browser-command.schema.json", "flow-execution-result.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R11", "R12", "R13", "Direct DB"],
        "owns": "Direct HTTP/WebSocket protocol client implementing 10-operation FlowExecutionPort",
        "does_not_own": "Browser automation, DOM interaction, database state, workflow logic",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Claude Opus 4.6 Thinking",
        "accept_model_fallback": "Gemini 3.1 Pro High",
        "pass_next": "R09-01",
        "hardening_notes": "10-op port conformance, session maintenance, token refresh, normalized error mapping."
    },
    {
        "id": "R09",
        "folder": "09_R09_BROWSER_WORKER",
        "name": "R09_browser_worker",
        "display_name": "Track A Browser Automation Worker",
        "layer": "Layer 4",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R09_BROWSER_WORKER.md",
        "contracts": ["browser-command.schema.json", "flow-execution-result.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R10", "R11", "R12", "R13", "Direct DB"],
        "owns": "Playwright/CDP automation implementing 10-operation FlowExecutionPort, 4-tier selector resolution (DOM, A11y, Visual, Agent Recovery), anti-abuse safety",
        "does_not_own": "Direct DB, direct API bridge, workflow state",
        "review_model": "Gemini 3.1 Pro High",
        "accept_model": "Claude Opus 4.6 Thinking",
        "accept_model_fallback": "Gemini 3.1 Pro High",
        "pass_next": "GATE-02",
        "hardening_notes": "Strict anti-abuse safety, human gate escalation on CAPTCHA/challenge, session isolation."
    },
    {
        "id": "R03",
        "folder": "10_R03_CREATIVE",
        "name": "R03_creative",
        "display_name": "Creative & Script Generation Engine",
        "layer": "Layer 2",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R03_CREATIVE.md",
        "contracts": ["domain-entities.schema.json"],
        "deps": ["R01", "R02", "R14"],
        "forbidden": ["R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R15", "Direct DB"],
        "owns": "LLM-assisted story/scene decomposition service, scene parsing, creative structured outputs",
        "does_not_own": "Database persistence, video rendering, browser execution",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R04-01",
        "hardening_notes": "Strict JSON schema enforcement on LLM outputs, deterministic fallback parsers."
    },
    {
        "id": "R04",
        "folder": "11_R04_ASSETS_CONTINUITY",
        "name": "R04_assets_continuity",
        "display_name": "Assets & Character Continuity Service",
        "layer": "Layer 2",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R04_ASSETS_CONTINUITY.md",
        "contracts": ["domain-entities.schema.json"],
        "deps": ["R01", "R02", "R14"],
        "forbidden": ["R03", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R15", "Direct DB"],
        "owns": "Asset catalog service, character reference embedding management, continuity token injection",
        "does_not_own": "Database persistence, video generation, workflow orchestration",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R05-01",
        "hardening_notes": "Character reference consistency across multi-shot sequences."
    },
    {
        "id": "R05",
        "folder": "12_R05_PROMPT_COMPILER",
        "name": "R05_prompt_compiler",
        "display_name": "Provider-Aware Prompt Compiler",
        "layer": "Layer 2",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R05_PROMPT_COMPILER.md",
        "contracts": ["provider-request.schema.json", "domain-entities.schema.json"],
        "deps": ["R01", "R02", "R04", "R14"],
        "forbidden": ["R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R15", "Direct DB"],
        "owns": "Prompt template compiler, dialect transformations (e.g. Veo, Luma, Runway syntax), negative prompt rules, safety filters",
        "does_not_own": "Direct video generation, storage, database",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R11-01",
        "hardening_notes": "Deterministic prompt compilation, parameter validation."
    },
    {
        "id": "R11",
        "folder": "13_R11_QC",
        "name": "R11_qc",
        "display_name": "Quality Control & Validation Service",
        "layer": "Layer 2",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R11_QC.md",
        "contracts": ["domain-entities.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R12", "R13", "Direct DB"],
        "owns": "Technical QC (FFprobe container, stream, resolution, framerate, duration check), Semantic QC (LLM/Vision scoring), bounded retry decision output",
        "does_not_own": "Database persistence, video stitching, video generation",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "R12-01",
        "hardening_notes": "Fast technical inspection before expensive semantic evaluation, quarantine DLQ."
    },
    {
        "id": "R12",
        "folder": "14_R12_MEDIA",
        "name": "R12_media",
        "display_name": "Media Processing & Assembly Service",
        "layer": "Layer 2",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R12_MEDIA.md",
        "contracts": ["domain-entities.schema.json"],
        "deps": ["R01", "R14"],
        "forbidden": ["R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R13", "Direct DB"],
        "owns": "FFmpeg stitching, audio track overlay, color normalization, video transcoding, final packaging",
        "does_not_own": "Database persistence, generation workflows",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "GATE-03",
        "hardening_notes": "Safe subprocess invocation, deterministic transcoding parameters."
    },
    {
        "id": "R13",
        "folder": "16_R13_OPERATOR_CONSOLE",
        "name": "R13_operator_console",
        "display_name": "Human-in-the-Loop Operator Console",
        "layer": "Layer 5",
        "blueprint": "01_FROZEN_RELEASE/v1.0.0/FROZEN_SPEC_CANDIDATE/03_repo_blueprints/R13_OPERATOR_CONSOLE.md",
        "contracts": ["domain-entities.schema.json", "event-envelope.schema.json"],
        "deps": ["R01", "R02", "R06", "R14"],
        "forbidden": ["R03", "R04", "R05", "R07", "R08", "R09", "R10", "R11", "R12", "R15", "Direct DB", "Worker Internals"],
        "owns": "Operator UI web application for human approval gates, generation inspection, error triage, DLQ replay triggers",
        "does_not_own": "Direct database mutations, worker execution internals",
        "review_model": "Gemini 3.7 Flash High",
        "accept_model": "Gemini 3.7 Flash High",
        "accept_model_fallback": "Gemini 3.7 Flash High",
        "pass_next": "GATE-04",
        "hardening_notes": "Web UI interacting strictly via R02 Core State REST/gRPC and R06 Temporal client APIs."
    }
]

print(f"Total Repos defined: {len(REPOS_DATA)}")
